FROM node:22-alpine AS build

WORKDIR /app

COPY frontend/event-manager-client/package*.json ./

RUN npm ci 

COPY frontend/event-manager-client/ ./

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]