services:

  postgres:
    image: postgres:17
    container_name: eventmanager-postgres
    environment:
      POSTGRES_DB: eventmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventmanager"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: ..
      dockerfile: docker/migrations/Dockerfile
    container_name: eventmanager-migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings_Database: >-
        Host=postgres;
        Port=5432;
        Database=eventmanager;
        Username=postgres;
        Password=postgres

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: eventmanager-backend
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings_Database: >-
        Host=postgres;
        Port=5432;
        Database=eventmanager;
        Username=postgres;
        Password=postgres;

      Jwt__Issuer: EventManager

      Jwt__Audience: EventManager.API

      Jwt__Secret: >-
        development-only-super-secret-key-change-this

      Jwt__AccessTokenMinutes: 15

      Jwt__RefreshTokenDays: 30

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: eventmanager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: eventmanager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    container_name: eventmanager-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: