services:

  postgres:
    image: postgres:17
    container_name: eventmanager-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  migrator:
    build:
      context: ..
      dockerfile: docker/migrations/Dockerfile
    container_name: eventmanager-migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__Database: >-
        Host=postgres;
        Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD}

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: eventmanager-backend
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      ConnectionStrings__Database: >-
        Host=postgres;
        Port=5432;
        Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};
        Password=${POSTGRES_PASSWORD};

      Jwt__Issuer: ${JWT_ISSUER}

      Jwt__Audience: ${JWT_AUDIENCE}

      Jwt__Secret: ${JWT_SECRET}

      Jwt__AccessTokenMinutes: 15

      Jwt__RefreshTokenDays: 30

      BootstrapAdmin__Enabled: ${BOOTSTRAP_ADMIN_ENABLED}
      BootstrapAdmin__Login: ${BOOTSTRAP_ADMIN_LOGIN}
      BootstrapAdmin__Password: ${BOOTSTRAP_ADMIN_PASSWORD}
      BootstrapAdmin__Email: ${BOOTSTRAP_ADMIN_EMAIL}
      BootstrapAdmin__FirstName: ${BOOTSTRAP_ADMIN_FIRST_NAME}
      BootstrapAdmin__LastName: ${BOOTSTRAP_ADMIN_LAST_NAME}
      BootstrapAdmin__BirthDate: "2002-08-27"

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: eventmanager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: eventmanager-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management
    container_name: eventmanager-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: